generic/urls.py
from django.urls import path
from django.views.generic import TemplateView

app_name = "generic"
urlpatterns = [
    path("", TemplateView.as_view(template_name="home.html"), name="home"),
    path("cgu", TemplateView.as_view(template_name="cgu.html"), name="cgu"),
    path(
        "legal-notice", TemplateView.as_view(template_name="legals.html"), name="legals"
    ),
]

main/urls.py
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.urls import include, path
from django.views.i18n import JavaScriptCatalog

from djatoms.admin import admin_site
from visits.views import bad_request, page_not_found, permission_denied, server_error

handler400 = bad_request
handler403 = permission_denied
handler404 = page_not_found
handler500 = server_error

urlpatterns = [
    path("", include("atlas.urls")),
    path("", include("generic.urls")),
    path("accounts/", include("users.urls")),
    path("contact/", include("contact.urls")),
    path("admin/", admin_site.urls),
    path(
        "jsi18n/",
        JavaScriptCatalog.as_view(),
        name="javascript-catalog",
    ),
]
if settings.DEBUG:
    import debug_toolbar

    urlpatterns.append(path("__debug__/", include(debug_toolbar.urls)))

urlpatterns = i18n_patterns(*urlpatterns)

# TODO : cache javascript-catalog :
# https://docs.djangoproject.com/en/4.2/topics/i18n/translation/#note-on-performance

users/urls.py
from django.urls import path

from .views import (
    DeleteProfileView,
    LoginView,
    LogoutView,
    PasswordChangeView,
    PasswordResetConfirmView,
    PasswordResetDoneView,
    PasswordResetView,
    ProfileView,
    RegistrationConfirmView,
    RegistrationDoneView,
    RegistrationView,
)

app_name = "users"

urlpatterns = [
    path("login/", LoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("profile/", ProfileView.as_view(), name="profile"),
    path("register/", RegistrationView.as_view(), name="register"),
    path("register/done", RegistrationDoneView.as_view(), name="register_done"),
    path(
        "register/confirm/<uidb64>/<token>/",
        RegistrationConfirmView.as_view(),
        name="register_confirm",
    ),
    path(
        "password_reset/",
        PasswordResetView.as_view(),
        name="password_reset",
    ),
    path(
        "password_reset/done/",
        PasswordResetDoneView.as_view(),
        name="password_reset_done",
    ),
    path(
        "reset/<uidb64>/<token>/",
        PasswordResetConfirmView.as_view(),
        name="password_reset_confirm",
    ),
    path("password_change/", PasswordChangeView.as_view(), name="password_change"),
    path("delete/", DeleteProfileView.as_view(), name="delete"),
]

users/models.py
from django.contrib.auth.models import (
    AbstractBaseUser,
    BaseUserManager,
    PermissionsMixin,
)
from django.db import models
from django.utils import timezone
from django.utils.translation import gettext_lazy as _


class UserManager(BaseUserManager):
    def _create_user(self, email, password, is_staff, is_superuser, **extra_fields):
        if not email:
            raise ValueError("Users must have an email address")
        now = timezone.now()
        email = self.normalize_email(email)
        user = self.model(
            email=email,
            is_staff=is_staff,
            is_active=True,
            is_superuser=is_superuser,
            last_login=now,
            date_joined=now,
            **extra_fields,
        )
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password, **extra_fields):
        return self._create_user(email, password, False, False, **extra_fields)

    def create_superuser(self, email, password, **extra_fields):
        user = self._create_user(email, password, True, True, **extra_fields)
        return user


class User(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(_("Email"), max_length=254, unique=True)
    first_name = models.CharField(
        _("First name"), max_length=254, null=True, blank=True
    )
    last_name = models.CharField(_("Last name"), max_length=254, null=True, blank=True)
    is_staff = models.BooleanField(_("Is staff"), default=False)
    is_superuser = models.BooleanField(_("Is superuser"), default=False)
    is_active = models.BooleanField(_("Is active"), default=True)
    last_login = models.DateTimeField(_("Last login"), null=True, blank=True)
    date_joined = models.DateTimeField(_("Date joined"), auto_now_add=True)

    USERNAME_FIELD = "email"
    EMAIL_FIELD = "email"
    REQUIRED_FIELDS = ["first_name", "last_name"]

    objects = UserManager()

    class Meta:
        get_latest_by = "date_joined"
        verbose_name = _("User")
        verbose_name_plural = _("Users")


# ADD SAML AUTH LATER but for now keep django's

users/forms.py
from crispy_forms.bootstrap import FormActions
from crispy_forms.helper import FormHelper
from crispy_forms.layout import HTML, ButtonHolder, Div, Field, Layout, Submit
from django import forms
from django.contrib.auth.forms import (
    AuthenticationForm,
    PasswordChangeForm,
    PasswordResetForm,
    SetPasswordForm,
    UserCreationForm,
)
from django.urls import reverse_lazy
from django.utils.html import mark_safe
from django.utils.text import format_lazy
from django.utils.translation import gettext_lazy as _

from djatoms.widgets import DisabledCheckboxInput

from .models import User


class UserCreationForm(UserCreationForm):
    usable_password = None

    class Meta:
        model = User
        fields = ("first_name", "last_name", "email", "password1", "password2")

    def __init__(self, *args, **kwargs):

        super().__init__(*args, **kwargs)
        self.fields["email"].widget.attrs.pop("autofocus", None)

        self.helper = FormHelper()
        self.helper.layout = Layout(
            Div(
                Div(Field("first_name"), css_class="col-6"),
                Div(Field("last_name"), css_class="col-6"),
                css_class="row",
            ),
            Field("email"),
            Field("password1"),
            Field("password2"),
            Field("cgu", value=0),
            ButtonHolder(
                Submit(
                    "submit",
                    _("REGISTER BUTTON Créer un compte"),
                    css_class="btn btn-primary disabled",
                    css_id="id-submit",
                ),
                css_class="text-center mb-3",
            ),
        )

    first_name = forms.CharField(max_length=50, label=_("Prénom"))
    last_name = forms.CharField(max_length=50, label=_("Nom"))
    email = forms.EmailField()
    cgu = forms.ChoiceField(
        choices=[(True, "")],
        widget=forms.CheckboxInput,
        label=mark_safe(
            format_lazy(
                "{read}<a href={link}>{name}</a>",
                read=_("REGISTER CHECK J'ai lu et j'accepte"),
                link=reverse_lazy("generic:cgu"),
                name=_("REGISTER CHECK CGU"),
            )
        ),
        required=False,
    )


class UsersFormMixin:

    button_text = ""

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.layout = Layout(
            Div(*self.fields),
            ButtonHolder(Submit("submit", self.button_text), css_class="text-center"),
        )


class PasswordResetForm(UsersFormMixin, PasswordResetForm):
    button_text = _("PASSWORD BUTTON Envoyer le mail")


class SetPasswordForm(UsersFormMixin, SetPasswordForm):
    button_text = _("PASSWORD BUTTON Réinitialiser")


class PasswordChangeForm(UsersFormMixin, PasswordChangeForm):
    button_text = _("PASSWORD BUTTON Valider")


class AuthenticationForm(UsersFormMixin, AuthenticationForm):
    button_text = _("LOGIN BUTTON Se connecter")

    class Meta:
        model = User
        fields = ("email", "password")

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["username"].widget.attrs.pop("autofocus", None)
        self.helper.form_show_errors = False


class DeleteProfileForm(forms.Form):
    class Meta:
        fields = "keep_diatom"

    keep_diatom = forms.ChoiceField(
        choices=[
            ("KEEP", _("DELETE CHOICE Conserver mes ajouts")),
            ("ANONYM", _("DELETE CHOICE Anonymiser mes ajouts")),
            ("DELETE", _("DELETE CHOICE Supprimer mes ajouts")),
        ],
        widget=forms.RadioSelect,
        label=_("DELETE MSG Choisissez une option pour vos contributions"),
    )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.helper = FormHelper()
        self.helper.layout = Layout(
            Div(*self.fields),
            Div(
                FormActions(
                    HTML(
                        """
                    <a type="button" class="btn btn-secondary" href={}>{}</a>
                    """.format(
                            reverse_lazy("users:profile"), _("DELETE BUTTON Annuler")
                        )
                    ),
                    Submit(
                        "submit",
                        _("DELETE BUTTON Supprimer"),
                        css_class="btn btn-danger",
                    ),
                ),
                css_class="text-end",
            ),
        )


class UserAdminChangeForm(forms.ModelForm):

    fields = [
        "first_name",
        "last_name",
        "email",
        "is_staff",
        "is_superuser",
        "last_login",
    ]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        if self.initial and "is_superuser" in self.initial.keys():
            if self.initial["is_superuser"]:
                self.fields["is_staff"] = forms.BooleanField(
                    widget=DisabledCheckboxInput, required=False
                )
            else:
                self.fields["is_staff"] = forms.BooleanField(required=False)

    is_superuser = forms.BooleanField(widget=DisabledCheckboxInput, required=False)

users/views.py
from django.contrib import messages
from django.contrib.auth import login
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.tokens import default_token_generator
from django.contrib.auth.views import (
    LoginView,
    LogoutView,
    PasswordChangeView,
    PasswordResetConfirmView,
    PasswordResetDoneView,
    PasswordResetView,
)
from django.contrib.sites.shortcuts import get_current_site
from django.core.mail import EmailMultiAlternatives
from django.shortcuts import redirect
from django.template.loader import render_to_string
from django.urls import reverse_lazy
from django.utils.encoding import force_bytes
from django.utils.html import strip_tags
from django.utils.http import urlsafe_base64_decode, urlsafe_base64_encode
from django.utils.translation import gettext_lazy as _
from django.views.generic import CreateView, DeleteView, ListView, TemplateView

from atlas.models import Diatom
from main.utils import refresh_materialized_view

from .forms import (
    AuthenticationForm,
    DeleteProfileForm,
    PasswordChangeForm,
    PasswordResetForm,
    SetPasswordForm,
    UserCreationForm,
)
from .models import User


class UsersViewMixin:
    template_name = "base_users.html"
    title = ""
    preform = None
    postform = None

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context["title"] = self.title
        context["preform"] = self.preform
        context["postform"] = self.postform
        return context


class LoginView(UsersViewMixin, LoginView):
    template_name = "login.html"
    form_class = AuthenticationForm
    redirect_authenticated_user = True

    title = _("LOGIN Title")


class LogoutView(LogoutView):
    http_method_names = ["get", "post", "options"]
    next_page = reverse_lazy("users:login")

    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect("users:profile")
        else:
            return redirect("users:login")


class ProfileView(LoginRequiredMixin, ListView):
    model = Diatom
    template_name = "profile.html"
    paginate_by = 10
    ordering = "-upload_date"

    def get_queryset(self):
        queryset = (
            Diatom.objects.filter(user_id=self.request.user.id)
            .values("id", "taxon__taxon_name", "upload_date")
            .order_by(self.get_ordering())
        )
        return queryset


class RegistrationView(CreateView):
    form_class = UserCreationForm
    template_name = "register.html"
    success_url = reverse_lazy("users:register_done")

    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect(reverse_lazy("users:profile"))
        return super().get(self.request, *args, **kwargs)

    def form_valid(self, form):

        user = form.save(commit=False)
        user.is_active = False
        user.save()

        current_site = get_current_site(self.request)
        message = render_to_string(
            "register_email.html",
            {
                "user": user,
                "domain": current_site.domain,
                "uid": urlsafe_base64_encode(force_bytes(user.pk)),
                "token": default_token_generator.make_token(user),
            },
        )

        email = EmailMultiAlternatives(
            subject=_("Account activation"),
            body=strip_tags(message),
            to=[form.cleaned_data["email"]],
        )
        email.attach_alternative(message, "text/html")
        email.send()
        return redirect(self.success_url)

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context["title"] = _("REGISTER Title")
        context["col_classes"] = "col-md-8 col-lg-5"
        return context


class RegistrationDoneView(UsersViewMixin, TemplateView):
    title = _("REGISTER TITLE Email Sent")
    postform = _("REGISTER MSG Email sent")

    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect(reverse_lazy("users:profile"))
        return super().get(self.request, *args, **kwargs)


class RegistrationConfirmView(TemplateView):
    template_name = "register_confirm.html"
    success_url = reverse_lazy("users:profile")

    def dispatch(self, *args, **kwargs):
        if self.request.user.is_authenticated:
            return redirect(reverse_lazy("users:profile"))

        uid = urlsafe_base64_decode(kwargs["uidb64"]).decode()
        user = User.objects.get(pk=uid)
        if default_token_generator.check_token(user, kwargs["token"]):
            user.is_active = True
            user.save()
            login(self.request, user)
            messages.success(self.request, _("REGISTER MSG Account activated"))
            return redirect(self.success_url)
        return self.render_to_response(
            {"validlink": False, "title": _("REGISTER TITLE Lien invalide")}
        )


class PasswordResetView(UsersViewMixin, PasswordResetView):
    email_template_name = "password_reset_email.html"
    html_email_template_name = "password_reset_email.html"
    success_url = reverse_lazy("users:password_reset_done")
    form_class = PasswordResetForm

    title = _("PASSWORD TITLE Forgotten Password")
    preform = _("PASSWORD MSG enter your mail")


class PasswordResetDoneView(UsersViewMixin, PasswordResetDoneView):
    title = _("PASSWORD TITLE Email Sent")
    preform = _("PASSWORD MSG Email sent")


class PasswordResetConfirmView(UsersViewMixin, PasswordResetConfirmView):
    model = User
    template_name = "password_reset_confirm.html"
    success_url = reverse_lazy("users:login")
    form_class = SetPasswordForm

    title = _("PASSWORD TITLE Reset")

    def form_valid(self, form):
        messages.success(self.request, _("PASSWORD MSG Password changed"))
        return super().form_valid(form)


class PasswordChangeView(UsersViewMixin, PasswordChangeView):
    form_class = PasswordChangeForm
    model = User
    success_url = reverse_lazy("users:profile")
    title = _("PASSWORD TITLE Change password")

    def form_valid(self, form):
        messages.success(self.request, _("PASSWORD MSG Password changed"))
        return super().form_valid(form)


class DeleteProfileView(LoginRequiredMixin, DeleteView):
    model = User
    form_class = DeleteProfileForm
    template_name = "delete.html"
    success_url = reverse_lazy("generic:home")

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context["title"] = _("DELETE Title")
        context["col_classes"] = "col-md-8 col-lg-6"
        return context

    def get_object(self):
        return self.request.user

    def form_valid(self, form):
        if form.cleaned_data["keep_diatom"] == "KEEP":
            self.request.user.is_active = False
            self.request.user.save()
            messages.warning(self.request, _("DELETE MSG Account inactive"))
            return redirect(self.success_url)
        elif form.cleaned_data["keep_diatom"] == "ANONYM":
            deleted_user = User.objects.get(first_name="Deleted")
            Diatom.objects.filter(user=self.request.user).update(user=deleted_user)
            messages.warning(self.request, _("DELETE MSG Account deleted"))
            return super().form_valid(form)
        else:
            s = super().form_valid(form)
            refresh_materialized_view("terato.children_diatoms")
            messages.warning(self.request, _("DELETE MSG All deleted"))
            return s

users/templates/base_users.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block title %}
    {{ title }}
{% endblock title %}
{% block content %}
    <div class="container min-vh-75">
        <div class="row justify-content-center align-items-center mt-5 pt-5">
            <div class="{% if col_classes %} {{ col_classes }} {% else %}col-md-5 col-lg-4{% endif %}">
                {% block login_msg %}
                {% endblock login_msg %}
                <div class="card">
                    <h5 class="card-header text-center">{{ title }}</h5>
                    <div class="card-body">
                        {% block pre-card-form %}
                            {% if preform %}
                                <div class="text-center{% if form %} mb-3{% endif %}">{{ preform }}</div>
                            {% endif %}
                        {% endblock pre-card-form %}
                        {% if form %}
                            {% crispy form %}
                        {% endif %}
                        {% block post-card-form %}
                            {% if postform %}
                                <div class="text-center{% if form %} mt-3{% endif %}">{{ postform }}</div>
                            {% endif %}
                        {% endblock post-card-form %}
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

users/templates/delete.html
{% extends "base_users.html" %}
{% load render_bundle from webpack_loader %}
{% block stylesheet %}
    {% render_bundle "delete.css" "css" "USERS" %}
{% endblock stylesheet %}

users/templates/login.html
{% extends "base_users.html" %}
{% load i18n %}
{% block login_msg %}
    {% if user.is_authenticated %}
        {% if next %}
            <div class="alert alert-danger">{% translate "LOGIN MSG Niveau d'accès insuffisant" %}</div>
        {% endif %}
    {% else %}
        {% if next %}
            <div class="alert alert-warning">{% translate "LOGIN MSG Connexion requise" %}</div>
        {% endif %}
        {% if form.errors %}
            <div class="alert alert-danger">{% translate "LOGIN MSG Identifiants invalides" %}</div>
        {% endif %}
    {% endif %}
{% endblock login_msg %}
{% block post-card-form %}
    <div class="text-center mt-3">
        <p>
            <a href="{% url 'users:password_reset' %}">{% translate "LOGIN MSG Mot de passe oublié" %}</a>
        </p>
        <p>
            {% translate "LOGIN MSG Pas encore de compte" %}
            <a href="{% url 'users:register' %}">{% translate "LOGIN MSG Créer un compte" %}</a>
        </p>
    </div>
{% endblock post-card-form %}

users/templates/password_reset_confirm.html
{% extends "base_users.html" %}
{% load i18n %}
{% block post-card-form %}
    {% if not validlink %}
        <div class="text-center">
            {% translate "PASSWORD MSG Lien invalide" %}
            <a href="{% url 'users:password_reset' %}">{% translate "PASSWORD MSG Demander une réinitialisation" %}</a>
        </div>
    {% endif %}
{% endblock post-card-form %}

users/templates/password_reset_email.html
{% load i18n %}
{% autoescape off %}
    <p>{% translate "PASSWORD MSG Hi" %} {{ user.first_name }},</p>
    <p>
        {% blocktranslate %}
        You're receiving this email because you requested a password reset for your user account at {{ site_name }}.
        {% endblocktranslate %}
    </p>
    <p>
        {% translate "PASSWORD MSG Lien réinitialisation" %}
        <br>
        {% block reset_link %}
            {{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}
        {% endblock reset_link %}
    </p>
    <p>{% translate "PASSWORD MSG Thanks for using" %}</p>
    <p>{% blocktranslate %}The {{ site_name }} team{% endblocktranslate %}</p>
{% endautoescape %}

users/templates/profile.html
{% extends "base.html" %}
{% load humanize %}
{% load i18n %}
{% load render_bundle from webpack_loader %}
{% block stylesheet %}
    {% render_bundle "profile.css" "css" "USERS" %}
{% endblock stylesheet %}
{% block title %}
    {% translate "PROFILE TITLE Profil" %}
{% endblock title %}
{% block content %}
    {% url 'atlas:contrib:diatom_upload' as link_upload %}
    <div class="container">
        <h2 class="my-4 text-center">{% translate "PROFILE TITLE Bonjour" %}, {{ user.first_name }}</h2>
        <div class="row justify-content-center">
            <div class="col-lg-8">
                <nav>
                    <div class="nav nav-tabs" id="nav-tab" role="tablist">
                        <button class="nav-link active"
                                id="contribs-tab"
                                data-bs-toggle="tab"
                                data-bs-target="#contribs"
                                type="button"
                                role="tab"
                                aria-controls="contribs"
                                aria-selected="true">{% translate "PROFILE TAB Vos contributions" %}</button>
                        <button class="nav-link"
                                id="info-tab"
                                data-bs-toggle="tab"
                                data-bs-target="#info"
                                type="button"
                                role="tab"
                                aria-controls="info"
                                aria-selected="false">{% translate "PROFILE TAB Profil" %}</button>
                    </div>
                </nav>
                <div class="tab-content">
                    <div class="tab-pane fade show active"
                         id="contribs"
                         role="tabpanel"
                         aria-labelledby="contribs-tab"
                         tabindex="0">
                        {% if page_obj %}
                            <div class="list-group list-group-flush">
                                {% for diatom in page_obj %}
                                    <a href="{% url 'atlas:consult:detail_diatom' diatom.id %}"
                                       class="list-group-item list-group-item-action">
                                        <div class="d-flex w-100 justify-content-between">
                                            <div class="d-flex">
                                                <div class="my-auto contrib-img-container">
                                                    <img class="contrib-img"
                                                         src="{% url 'atlas:api:generate_thumbnail' diatom.id %}"
                                                         alt="no picture" />
                                                </div>
                                                <h6 class="my-auto ms-2">{{ diatom.taxon__taxon_name }}</h6>
                                            </div>
                                            <span class="my-auto d-none d-sm-flex">{{ diatom.upload_date|naturaltime }}</span>
                                        </div>
                                    </a>
                                {% endfor %}
                            </div>
                            <nav class="mt-3" aria-label="User's contributions">
                                <ul class="pagination justify-content-end">
                                    {% if page_obj.has_previous %}
                                        {% if page_obj.previous_page_number > 1 %}
                                            <li class="page-item">
                                                <a class="page-link" href="?page=1">1</a>
                                            </li>
                                            {% if page_obj.previous_page_number > 2 %}
                                                <li class="page-item disabled">
                                                    <a class="page-link">...</a>
                                                </li>
                                            {% endif %}
                                        {% endif %}
                                        <li class="page-item">
                                            <a class="page-link" href="?page={{ page_obj.previous_page_number }}">{{ page_obj.previous_page_number }}</a>
                                        </li>
                                    {% endif %}
                                    <li class="page-item active" aria-current="page">
                                        <a class="page-link" href="#">{{ page_obj.number }}</a>
                                    </li>
                                    {% if page_obj.has_next %}
                                        <li class="page-item">
                                            <a class="page-link" href="?page={{ page_obj.next_page_number }}">{{ page_obj.next_page_number }}</a>
                                        </li>
                                        {% if page_obj.next_page_number < page_obj.paginator.num_pages %}
                                            {% if page_obj.next_page_number < page_obj.paginator.num_pages|add:'-1' %}
                                                <li class="page-item disabled">
                                                    <a class="page-link">...</a>
                                                </li>
                                            {% endif %}
                                            <li class="page-item">
                                                <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">{{ page_obj.paginator.num_pages }}</a>
                                            </li>
                                        {% endif %}
                                    {% endif %}
                                </ul>
                            </nav>
                        {% else %}
                            <div class="mt-3">
                                {% blocktranslate %}
                                    Vos contributions apparaîtront ici, dès lors que vous aurez <a href="{{ link_upload }}">ajouté une diatomée</a>.
                                {% endblocktranslate %}
                            </div>
                        {% endif %}
                    </div>
                    <div class="tab-pane fade"
                         id="info"
                         role="tabpanel"
                         aria-labelledby="info-tab"
                         tabindex="0">
                        <div class="card mt-5">
                            <div class="card-body">
                                <p>
                                    <b>{% translate "PROFILE MSG Prénom" %}</b> {{ user.first_name }}
                                </p>
                                <p>
                                    <b>{% translate "PROFILE MSG Nom" %}</b> {{ user.last_name }}
                                </p>
                                <p>
                                    <b>{% translate "PROFILE MSG Email" %}</b> {{ user.email }}
                                </p>
                                <p>
                                    <a href="{% url 'users:password_change' %}">{% translate "PROFILE MSG Changer mdp" %}</a>
                                </p>
                                <p>
                                    <a href="{% url 'users:delete' %}">{% translate "PROFILE MSG Supprimer mon compte" %}</a>
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

users/templates/register.html
{% extends "base_users.html" %}
{% load i18n %}
{% load render_bundle from webpack_loader %}
{% block post-card-form %}
    {% url 'generic:cgu' as link_cgu %}
    <div class="text-center">
        {% translate "REGISTER MSG Déjà un compte" %}
        <a href="{% url 'users:login' %}">{% translate "REGISTER MSG Connectez-vous" %}</a>
    </div>
{% endblock post-card-form %}
{% block script %}
    {{ block.super }}
    {% render_bundle "register" "js" "USERS" %}
{% endblock script %}

users/templates/register_confirm.html
{% extends "base_users.html" %}
{% load i18n %}
{% block post-card-form %}
    {% if not validlink %}
        <div class="text-center">
            {% translate "REGISTER MSG Lien invalide" %}
            <a href="{% url 'users:register' %}">{% translate "REGISTER MSG Recommencer" %}</a>.
        </div>
    {% endif %}
{% endblock post-card-form %}

users/templates/register_email.html
{% load i18n %}
{% autoescape off %}
    <p>{% translate "REGISTER MSG Hi" %} {{ user.first_name }},</p>
    <p>
        {% blocktranslate %}
        You're receiving this email because you requested an user account creation at {{ domain }}.
        {% endblocktranslate %}
    </p>
    <p>
        {% translate "REGISTER MSG Lien réinitialisation" %}
        <br>
        {% block reset_link %}
            {{ domain }}{% url 'users:register_confirm' uidb64=uid token=token %}
        {% endblock reset_link %}
    </p>
    <p>{% translate "REGISTER MSG Thanks for using" %}</p>
    <p>{% blocktranslate %}The {{ domain }} team{% endblocktranslate %}</p>
{% endautoescape %}