atlas/urls.py
from django.urls import include, path

from . import views

contrib_patterns = [
    path(
        "diatom/delete/<int:pk>/",
        views.DiatomDeleteView.as_view(),
        name="diatom_delete",
    ),
    path(
        "diatom/modify/<int:pk>/", views.ModifyFormView.as_view(), name="diatom_modify"
    ),
    path("diatom/upload/", views.UploadFormView.as_view(), name="diatom_upload"),
]

consult_patterns = [
    path("diatom/<int:pk>/", views.DiatomDetailView.as_view(), name="detail_diatom"),
    path("taxons/", views.TaxonListView.as_view(), name="taxons"),
    path("taxons/<int:pk>/", views.TaxonDetailView.as_view(), name="detail_taxon"),
]

api_patterns = [
    path("generate_image/<int:diatom_id>", views.generate_image, name="generate_image"),
    path(
        "generate_thumbnail/<int:diatom_id>",
        views.generate_thumbnail,
        name="generate_thumbnail",
    ),
    path("search/diatom", views.search_diatom, name="diatom_search"),
    path("search/inventory", views.search_inventory, name="inventory_search"),
    path("search/station", views.search_station, name="station_search"),
    path("search/taxon", views.search_taxon, name="taxon_search"),
    path(
        "stations_geojson",
        views.StationsLayerView.as_view(),
        name="stations_data",
    ),
    path(
        "contribs_geojson",
        views.ContributionsLayerView.as_view(),
        name="contribs_data",
    ),
    path("taxons_json/", views.TaxonJson.as_view(), name="taxons_json"),
]

app_name = "atlas"
urlpatterns = [
    path("", include((contrib_patterns, app_name), namespace="contrib")),
    path("", include((consult_patterns, app_name), namespace="consult")),
    path("", include((api_patterns, app_name), namespace="api")),
]

contact/urls.py
from django.urls import path

from .views import ContactView, FlagView

app_name = "contact"
urlpatterns = [
    path("", ContactView.as_view(), name="contact"),
    path("flag/<int:pk>/", FlagView.as_view(), name="flag"),
]

main/urls.py
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.urls import include, path
from django.views.i18n import JavaScriptCatalog

from djatoms.admin import admin_site
from visits.views import bad_request, page_not_found, permission_denied, server_error

handler400 = bad_request
handler403 = permission_denied
handler404 = page_not_found
handler500 = server_error

urlpatterns = [
    path("", include("atlas.urls")),
    path("", include("generic.urls")),
    path("accounts/", include("users.urls")),
    path("contact/", include("contact.urls")),
    path("admin/", admin_site.urls),
    path(
        "jsi18n/",
        JavaScriptCatalog.as_view(),
        name="javascript-catalog",
    ),
]
if settings.DEBUG:
    import debug_toolbar

    urlpatterns.append(path("__debug__/", include(debug_toolbar.urls)))

urlpatterns = i18n_patterns(*urlpatterns)

# TODO : cache javascript-catalog :
# https://docs.djangoproject.com/en/4.2/topics/i18n/translation/#note-on-performance

atlas/models/codes.py
from django.contrib.gis.db import models
from django.contrib.postgres.indexes import BTreeIndex


class CodeType(models.Model):
    id = models.AutoField(primary_key=True, db_column="identifier_type_id")
    code_type_name = models.CharField(db_column="identifier_type_name")

    class Meta:
        db_table = 'diatom"."identifier_type'
        db_table_comment = "List of types of identifiers"
        managed = False

    def __str__(self):
        return self.code_type_name


class TaxonCode(models.Model):
    id = models.AutoField(primary_key=True, db_column="taxon_identifier_id")
    taxon = models.ForeignKey("Taxon", models.DO_NOTHING)
    code = models.CharField()
    code_type = models.ForeignKey(
        "CodeType", models.DO_NOTHING, db_column="identifier_type_id"
    )

    class Meta:
        db_table = 'diatom"."taxon_identifier'
        db_table_comment = "List of codes used to identifier a taxon"
        managed = False

        indexes = [
            BTreeIndex(
                fields=["code", "code_type"], name="taxon_identifier_type_code_idx"
            ),
        ]

    def __str__(self):
        return self.code

atlas/models/diatom.py
from base64 import b64encode

from django.conf import settings
from django.contrib import admin
from django.contrib.gis.db import models
from django.contrib.postgres.indexes import BTreeIndex
from django.utils.html import mark_safe
from django.utils.translation import gettext_lazy as _


class Health(models.Model):
    id = models.AutoField(primary_key=True, db_column="health_id")
    health_abb = models.CharField(
        max_length=1, db_comment="One-letter abbreviation of health status"
    )
    health_full = models.CharField(
        max_length=15, db_comment="Full name for health status (fallback)"
    )

    class Meta:
        db_table = 'terato"."health'
        db_table_comment = "Health status options for uploaded diatoms"
        managed = False

    def __str__(self):
        return self.health_full


class Diatom(models.Model):

    id = models.AutoField(primary_key=True, db_column="diatom_id")
    taxon = models.ForeignKey(
        "Taxon", models.DO_NOTHING, db_column="taxon_id", verbose_name=_("Taxon")
    )
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE, verbose_name=_("User")
    )
    health = models.ForeignKey(
        "Health", models.DO_NOTHING, db_column="health_id", verbose_name=_("Health")
    )
    inventory = models.ForeignKey(
        "Inventory",
        models.DO_NOTHING,
        null=True,
        blank=True,
        db_column="inventory_id",
        verbose_name=_("Inventory"),
    )
    station = models.ForeignKey(
        "Station",
        models.DO_NOTHING,
        null=True,
        blank=True,
        db_column="station_id",
        verbose_name=_("Station"),
    )
    sampling_date = models.DateTimeField(
        _("Sampling date"), null=True, blank=True, db_comment="Sampling date"
    )

    photo = models.BinaryField(db_comment="Entire image data", editable=True)
    photo_thumbnail = models.BinaryField(db_comment="Thumbnail image data")
    filename = models.CharField(
        _("Filename"),
        db_comment="Original name of image file",
        db_column="photo_filename",
    )
    height = models.IntegerField(db_comment="Height of image, in pixels")
    width = models.IntegerField(db_comment="Width of image, in pixels")
    scale = models.DecimalField(
        _("Scale"),
        max_digits=16,
        decimal_places=10,
        null=True,
        blank=True,
        db_comment="100px represent this much micrometers",
        help_text="100px represent this much micrometers",
    )
    upload_date = models.DateTimeField(
        _("Upload date"), auto_now=False, auto_now_add=True, db_comment="Upload date"
    )
    photo_author = models.CharField(
        _("Photo author"),
        null=True,
        blank=True,
        db_comment="Original author of the photo",
    )
    photo_doi = models.CharField(
        _("Photo DOI"),
        null=True,
        blank=True,
        db_comment="DOI of the publication where the photo first appeared",
    )

    def __str__(self):
        return self.filename

    def get_real_width(self):
        if self.scale:
            return round((10 * 100) / self.scale, 1)
        else:
            return None

    @admin.display(description=_("Thumbnail"))
    def thumbnail_tag(self):
        return mark_safe(
            '<img height=45 src="data: image/png; base64, %s" />'
            % (b64encode(self.photo).decode("utf8"))
        )

    class Meta:
        db_table = 'terato"."diatom'
        managed = False
        verbose_name = _("Diatom")
        verbose_name_plural = _("Diatoms")

        indexes = [
            BTreeIndex(fields=["taxon"], name="diatom_taxon_id_idx"),
            BTreeIndex(fields=["user"], name="diatom_user_id_idx"),
            BTreeIndex(fields=["health"], name="diatom_health_id_idx"),
        ]


class DiatomChildren(models.Model):

    diatom = models.ForeignKey(
        "Diatom",
        on_delete=models.DO_NOTHING,
        db_column="diatom_id",
        related_name="children",
    )
    health = models.IntegerField(db_column="health_id")
    taxon = models.CharField(db_column="taxon_name")
    ancestor = models.IntegerField(db_column="taxon_ancestor")
    upload_date = models.DateTimeField()

    class Meta:
        db_table = 'terato"."children_diatoms'
        managed = False

        indexes = [
            BTreeIndex(fields=["ancestor"], name="children_diatoms_ancestor_id_idx"),
            BTreeIndex(fields=["health"], name="children_diatoms_health_id_idx"),
        ]

atlas/views/detail_diatom.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _
from django.views.generic import DeleteView, DetailView

from contact.forms import FlagForm
from main.utils import refresh_materialized_view

from ..models import Diatom, DiatomDefoFactor


class DiatomDetailView(DetailView):
    model = Diatom
    template_name = "detail_diatom.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["flag_form"] = FlagForm(
            initial={
                "diatom": self.object,
            }
        )
        return context


class DiatomDeleteView(LoginRequiredMixin, DeleteView):
    model = Diatom
    success_url = reverse_lazy("users:profile")

    def form_valid(self, form):
        DiatomDefoFactor.objects.filter(diatom=self.object).delete()
        self.object.delete()
        refresh_materialized_view("terato.children_diatoms")
        messages.success(self.request, _("DELETE MSG Diatomée supprimée"))
        return redirect(self.get_success_url())

    def get(self, request, *args, **kwargs):
        return redirect(
            reverse_lazy("atlas:consult:detail_diatom", args=[kwargs["pk"]])
        )

atlas/views/leaflet.py
from django.db.models import Count

from djatoms.views import LeafletLayerView

from ..models import Station


class StationsLayerView(LeafletLayerView):

    model = Station
    properties = ["station_id", "station_code", "commune", "station_name"]

    def get_queryset(self):

        sel = self.request.GET.get("arg")
        if not sel:
            sel = -1

        qs = Station.objects.filter(pk=sel)
        if all([x in self.request.GET for x in ("x0", "x1", "y0", "y1")]):
            qs |= super().get_queryset()
        return qs


class ContributionsLayerView(LeafletLayerView):

    model = Station
    properties = [
        "station_id",
        "station_code",
        "commune",
        "station_name",
        "diatom__count",
    ]

    def get_queryset(self):

        taxon = self.request.GET.get("arg")

        if taxon:
            qs = Station.objects.filter(diatom__children__ancestor=taxon).annotate(
                diatom__count=Count("diatom__children__diatom")
            )
            qs &= super().get_queryset()
            return qs
        return Station.objects.none()

atlas/views/search.py
from datetime import datetime as dt
from datetime import timedelta

from django.contrib.postgres.aggregates import StringAgg
from django.db.models import CharField, F, Q, Value
from django.db.models.functions import Concat, ExtractDay, Greatest, Least, NullIf
from django.http import JsonResponse

from ..models import DiatomChildren, Inventory, Station, TaxonCode


def search_taxon(request):

    if request.GET.get("term"):

        taxon = request.GET.get("term").split(",")[0]

        if request.GET.get("pk") and taxon.isdigit():
            object_list = TaxonCode.objects.filter(taxon__id=int(taxon)).select_related(
                "taxon"
            )
        else:
            object_list = TaxonCode.objects.filter(
                Q(taxon__taxon_name__istartswith=taxon) | Q(code__istartswith=taxon)
            ).select_related("taxon")

        object_list = (
            TaxonCode.objects.filter(taxon__id__in=object_list.values("taxon__id"))
            .filter(taxon__freshwater_diatom=True)
            .filter(taxon__is_taxon=True)
            .values("taxon")
            .distinct()
            .annotate(
                label=Concat(
                    F("taxon__taxon_name"),
                    NullIf(
                        Concat(
                            Value(", "),
                            StringAgg(
                                "code",
                                delimiter=", ",
                                distinct=True,
                                ordering="-code",
                            ),
                            output_field=CharField(),
                        ),
                        Value(", "),
                    ),
                ),
                value=F("taxon__id"),
            )
            .order_by("taxon__taxon_name")
            .values("label", "value")
        )
        return JsonResponse(list(object_list), safe=False)
    return JsonResponse([], safe=False)


def search_station(request):

    if request.GET.get("term"):
        station = request.GET.get("term")

        if request.GET.get("pk") and station.isdigit():
            object_list = Station.objects.filter(pk=int(station))
        else:
            object_list = Station.objects.filter(
                Q(station_name__icontains=station) | Q(commune__istartswith=station)
            ).distinct()

        object_list = object_list.annotate(
            label=Concat(
                F("station_name"),
                NullIf(
                    Concat(Value(", "), F("commune")),
                    Value(", "),
                ),
            ),
            value=F("station_id"),
        ).values("label", "value")

        return JsonResponse(list(object_list), safe=False)
    return JsonResponse([], safe=False)


def search_diatom(request):

    if request.GET.get("taxon") and request.GET.get("health"):
        num_per_page = 10

        taxon = request.GET.get("taxon")
        health = request.GET.get("health")

        try:
            page = int(request.GET.get("page", 1))
        except ValueError:
            page = 1

        if page < 0:
            offset = ((-1) * page - 1) * num_per_page
            qs = (
                DiatomChildren.objects.filter(ancestor=taxon)
                .filter(health=health)
                .order_by("upload_date")[offset : offset + num_per_page]  # noqa: 203
                .values_list("diatom", "taxon")
            )
        else:
            offset = (page - 1) * num_per_page
            qs = (
                DiatomChildren.objects.filter(ancestor=taxon)
                .filter(health=health)
                .order_by("-upload_date")[offset : offset + num_per_page]  # noqa: 203
                .values_list("diatom", "taxon")
            )

        results = [{"id": obj[0], "taxon": obj[1]} for obj in qs]

        return JsonResponse(results, safe=False)
    return JsonResponse([], safe=False)


def search_inventory(request):
    if request.GET.get("date", None) and request.GET.get("station", None):

        try:
            date = dt.strptime(request.GET.get("date"), "%Y-%m-%d")
            station = request.GET.get("station")

            inventory = (
                Inventory.objects.filter(
                    Q(station=station)
                    & Q(inventory_type=1)
                    & Q(inventory_date__lte=date + timedelta(15))
                    & Q(inventory_date__gte=date - timedelta(60))
                )
                .annotate(
                    ecart=ExtractDay(
                        Greatest(date, F("inventory_date"))
                        - Least(date, F("inventory_date"))
                    )
                )
                .order_by("ecart")
            )

            if inventory:
                return JsonResponse(
                    {
                        "inventory": inventory[0].inventory_id,
                        "date": inventory[0].inventory_date.date(),
                    }
                )
        except ValueError:
            # happens if date can't be stripped
            return JsonResponse([], safe=False)

        return JsonResponse({"inventory": -1})
    return JsonResponse([], safe=False)

atlas/views/utils.py
import requests
from django.http import Http404, HttpResponse

from ..models import Diatom


def generate_image(request, diatom_id):
    try:
        diatom = Diatom.objects.get(pk=diatom_id)
        return HttpResponse(diatom.photo, content_type="image/PNG")
    except Diatom.DoesNotExist:
        raise Http404


def generate_thumbnail(request, diatom_id):
    try:
        thumbnail = Diatom.objects.get(pk=diatom_id).photo_thumbnail
        return HttpResponse(thumbnail, content_type="image/PNG")
    except Diatom.DoesNotExist:
        raise Http404


def check_doi(user_input):
    if "doi.org" not in user_input:
        user_input = "https://doi.org/" + user_input

    try:
        response = requests.head(user_input)
        if response.status_code == 302 and response.headers["location"]:
            return True
        elif response.status_code in [301, 404]:
            return False
        else:
            print(
                "Unexpected status code while checking \
                    the DOI given by the user: {}".format(
                    user_input
                )
            )
    except Exception:
        print(
            "An error occurred while checking the DOI given by the user: {}".format(
                user_input
            )
        )
        return False

atlas/templates/detail_diatom.html
{% extends "base_detail.html" %}
{% load i18n %}
{% load render_bundle from webpack_loader %}
{% load webpack_static from webpack_loader %}
{% load crispy_forms_tags %}
{% block title %}
    {% translate "DIATOM TITLE" %}
{% endblock title %}
{% block stylesheet %}
    {{ block.super }}
    {% render_bundle "detail_diatom" "css" "ATLAS" %}
{% endblock stylesheet %}
{% block tree %}
    {% with diatom.taxon as taxon %}{{ block.super }}{% endwith %}
{% endblock tree %}
{% block detail %}
    <div class="col-8 col-lg-7 order-1 order-lg-2 pt-5">
        <div class="row gx-5">
            <div class="col-xl-1"></div>
            <div class="col-xl-9">
                <div class="card">
                    <div class="row g-0">
                        <div id="image-column"
                             class="col-md-4 px-auto d-flex flex-column justify-content-center align-items-center">
                            <div id="image-container" class="d-flex justify-content-center">
                                <img class="rounded detail-image"
                                     src="{% url 'atlas:api:generate_image' diatom.id %}"
                                     alt="{% translate "Photo non disponible." %}">
                            </div>
                            <div id="scale-container" class="card-text text-center mt-3">
                                {% if diatom.get_real_width %}
                                    <div id="scale" class="text-bg-primary">
                                        {{ diatom.get_real_width|json_script:"scale-width" }}
                                        {{ diatom.width|json_script:"img-width" }}
                                        {{ diatom.height|json_script:"img-height" }}
                                    </div>
                                    <p id="scale-text">10 µm</p>
                                {% endif %}
                            </div>
                        </div>
                        <div class="col-md-8 d-flex flex-column justify-content-between">
                            <div class="card-body">
                                <div class="d-flex flex-wrap align-items-center justify-content-between">
                                    <h4 class="card-title">{{ diatom.taxon.taxon_name }}</h4>
                                    <div class="btn-group btn-group-sm">
                                        {% if user.diatom_set.all %}
                                            <button id="btn-flag"
                                                    class="btn btn-outline-secondary"
                                                    type="button"
                                                    data-bs-toggle="modal"
                                                    data-bs-target="#flag-modal"
                                                    title="{% translate "DIATOM CONTENT Signaler" %}">
                                                <img class="detail-icon"
                                                     src="{% webpack_static 'atlas/img/flag.svg' 'ATLAS' %}"
                                                     alt="{% translate "DIATOM CONTENT Signaler" %}">
                                            </button>
                                        {% endif %}
                                        {% if user == diatom.user or user.is_superuser %}
                                            {% url "atlas:contrib:diatom_modify" diatom.id as modify_url %}
                                            <a id="btn-modify"
                                               class="btn btn-outline-secondary"
                                               href="{{ modify_url }}"
                                               title="{% translate "MODIFY TITLE" %}">
                                                <img class="detail-icon"
                                                     src="{% webpack_static 'atlas/img/pencil-square.svg' 'ATLAS' %}"
                                                     alt="{% translate "MODIFY TITLE" %}">
                                            </a>
                                            <button id="btn-delete"
                                                    class="btn btn-outline-secondary"
                                                    type="button"
                                                    data-bs-toggle="modal"
                                                    data-bs-target="#delete-modal"
                                                    title="{% translate "DIATOM CONTENT Supprimer" %}">
                                                <img class="detail-icon"
                                                     src="{% webpack_static 'atlas/img/trash3.svg' 'ATLAS' %}"
                                                     alt="{% translate "DIATOM CONTENT Supprimer" %}">
                                            </button>
                                        {% endif %}
                                    </div>
                                </div>
                                <div class="mt-2">
                                    <p class="card-text">
                                        <small class="text-body-secondary">{% translate "DIATOM CONTENT Ajoutée le" %} {{ diatom.upload_date|date:'DATE_FORMAT' }} {% translate "DIATOM CONTENT Ajoutée par" %}
                                            {% if diatom.user.first_name == 'Deleted' %}
                                                {% translate "DIATOM CONTENT Utilisateur supprimé" %}
                                            {% else %}
                                                {{ diatom.user.first_name }} {{ diatom.user.last_name }}
                                            {% endif %}
                                        </small>
                                    </p>
                                </div>
                                <div class="card-text mt-5">
                                    {% if diatom.sampling_date and diatom.station.commune %}
                                        <p>
                                            {% translate "DIATOM CONTENT Prélevée le" %} {{ diatom.sampling_date|date:'DATE_FORMAT' }} {% translate "DIATOM CONTENT sur la commune de" %} {{ diatom.station.commune }}.
                                        </p>
                                    {% endif %}
                                    {% if diatom.photo_author %}<p>© {{ diatom.photo_author }}</p>{% endif %}
                                    {% if diatom.photo_doi %}
                                        <p>
                                            {% blocktranslate with diatom.photo_doi as link %}
                                                Cette photo a été publiée <a href="https://doi.org/{{link}}" target="_blank">ici.</a>
                                            {% endblocktranslate %}
                                        </p>
                                    {% endif %}
                                    <p>{% translate "DIATOM CONTENT Statut terato" %} : {{ diatom.health|lower }}</p>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="card-footer text-end">
                        <a href="{% url 'atlas:consult:detail_taxon' diatom.taxon.id %}">{% translate "DIATOM CONTENT Revenir au taxon" %}</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="modal fade"
         id="delete-modal"
         data-bs-backdrop="static"
         data-bs-keyboard="false"
         tabindex="-1"
         aria-labelledby="delete-modal-title"
         aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title mx-auto" id="delete-modal-title">{% translate "DIATOM CONTENT Supprimer" %}</h5>
                </div>
                <form action="{% url 'atlas:contrib:diatom_delete' diatom.id %}"
                      method="post">
                    {% csrf_token %}
                    <div class="modal-body text-center">
                        <p>{% translate "DIATOM CONTENT supprimer cette contribution ?" %}</p>
                        <p>{% translate "DIATOM CONTENT action irrréversible" %}</p>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">{% translate "AJOUT BUTTON Retour" %}</button>
                        <button type="submit" class="btn btn-danger" value="Confirm">{% translate "DIATOM CONTENT Supprimer" %}</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <div class="modal fade"
         id="flag-modal"
         data-bs-backdrop="static"
         data-bs-keyboard="false"
         tabindex="-1"
         aria-labelledby="flag-modal-title"
         aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title mx-auto" id="flag-modal-title">{% translate "DIATOM CONTENT Signaler" %}</h5>
                </div>
                <form action="{% url 'contact:flag' diatom.id %}" method="post">
                    <div class="modal-body">
                        {% csrf_token %}
                        {% for field in flag_form %}{{ field | as_crispy_field }}{% endfor %}
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">{% translate "AJOUT BUTTON Retour" %}</button>
                        <button type="submit" class="btn btn-danger" value="Confirm">{% translate "DIATOM CONTENT Signaler" %}</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock detail %}
{% block script %}
    {{ block.super }}
    {% render_bundle "detail_diatom" "js" "ATLAS" %}
{% endblock script %}

atlas/templates/diatom_modify.html
{% extends "base_diatom.html" %}
{% load i18n %}
{% load render_bundle from webpack_loader %}
{% block title %}
    {% translate "MODIFY TITLE" %}
{% endblock title %}
{% block stylesheet %}
    {{ block.super }}
    {% render_bundle "diatom_modify" "css" "ATLAS" %}
{% endblock stylesheet %}
{% block before %}
    {% translate "MODIFY TITLE" %}
{% endblock before %}
{% block step1 %}
    <div class="row align-items-center gx-5">
        <div class="col-md-9 c-border-md-right c-border-success pt-3 pb-1 order-2 order-md-1"
             id="col-photo">
            <div class="uploaded-container mb-4">{{ form.photo }}</div>
        </div>
        <div class="col-md-3 pt-3 mb-3 order-1 order-md-2">
            <div>{% translate "MODIFY HELPER Sélection photo" %}</div>
        </div>
    </div>
{% endblock step1 %}
{% block endbutton %}
    {% translate "MODIFY BUTTON Envoyer" %}
{% endblock endbutton %}
{% block script %}
    {{ block.super }}
    {% render_bundle "diatom_modify" "js" "ATLAS" %}
{% endblock script %}

atlas/templates/diatom_upload.html
{% extends "base_diatom.html" %}
{% load i18n %}
{% load render_bundle from webpack_loader %}
{% load crispy_forms_tags %}
{% block title %}
    {% translate "AJOUT TITLE" %}
{% endblock title %}
{% block stylesheet %}
    {{ block.super }}
    {% render_bundle "diatom_upload" "css" "ATLAS" %}
{% endblock stylesheet %}
{% block before %}
    {% translate "AJOUT TITLE" %}
{% endblock before %}
{% block step1 %}
    <div class="row align-items-center gx-5">
        <div class="col-md-9 c-border-md-right c-border-danger pt-3 order-2 order-md-1"
             id="col-photo">
            {{ form.photo | as_crispy_field }}
            <div id="format-not-valid" class="alert alert-danger" hidden="true">
                {% translate "AJOUT MESSAGE Format non pris en charge" %}
            </div>
        </div>
        <div class="col-md-3 pt-3 mb-3 order-1 order-md-2">
            <div>{% translate "AJOUT HELPER Sélection photo" %}</div>
        </div>
    </div>
    <div class="row align-items-center gx-5 mt-3" id="crop-row">
        <div class="col-md-9 c-border-md-right py-1 order-2 order-md-1">
            <div>
                <img id="imagecan" alt="{% translate "AJOUT ALT Cropper" %}">
            </div>
        </div>
        <div class="col-md-3 pt-3 mb-3 order-1 order-md-2">{% translate "AJOUT HELPER Recadrage photo" %}</div>
    </div>
{% endblock step1 %}
{% block endbutton %}
    {% translate "AJOUT BUTTON Envoyer" %}
{% endblock endbutton %}
{% block script %}
    {{ block.super }}
    {% render_bundle "diatom_upload" "js" "ATLAS" %}
{% endblock script %}