contact/urls.py
from django.urls import path

from .views import ContactView, FlagView

app_name = "contact"
urlpatterns = [
    path("", ContactView.as_view(), name="contact"),
    path("flag/<int:pk>/", FlagView.as_view(), name="flag"),
]

generic/urls.py
from django.urls import path
from django.views.generic import TemplateView

app_name = "generic"
urlpatterns = [
    path("", TemplateView.as_view(template_name="home.html"), name="home"),
    path("cgu", TemplateView.as_view(template_name="cgu.html"), name="cgu"),
    path(
        "legal-notice", TemplateView.as_view(template_name="legals.html"), name="legals"
    ),
]

main/urls.py
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.urls import include, path
from django.views.i18n import JavaScriptCatalog

from djatoms.admin import admin_site
from visits.views import bad_request, page_not_found, permission_denied, server_error

handler400 = bad_request
handler403 = permission_denied
handler404 = page_not_found
handler500 = server_error

urlpatterns = [
    path("", include("atlas.urls")),
    path("", include("generic.urls")),
    path("accounts/", include("users.urls")),
    path("contact/", include("contact.urls")),
    path("admin/", admin_site.urls),
    path(
        "jsi18n/",
        JavaScriptCatalog.as_view(),
        name="javascript-catalog",
    ),
]
if settings.DEBUG:
    import debug_toolbar

    urlpatterns.append(path("__debug__/", include(debug_toolbar.urls)))

urlpatterns = i18n_patterns(*urlpatterns)

# TODO : cache javascript-catalog :
# https://docs.djangoproject.com/en/4.2/topics/i18n/translation/#note-on-performance

users/urls.py
from django.urls import path

from .views import (
    DeleteProfileView,
    LoginView,
    LogoutView,
    PasswordChangeView,
    PasswordResetConfirmView,
    PasswordResetDoneView,
    PasswordResetView,
    ProfileView,
    RegistrationConfirmView,
    RegistrationDoneView,
    RegistrationView,
)

app_name = "users"

urlpatterns = [
    path("login/", LoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("profile/", ProfileView.as_view(), name="profile"),
    path("register/", RegistrationView.as_view(), name="register"),
    path("register/done", RegistrationDoneView.as_view(), name="register_done"),
    path(
        "register/confirm/<uidb64>/<token>/",
        RegistrationConfirmView.as_view(),
        name="register_confirm",
    ),
    path(
        "password_reset/",
        PasswordResetView.as_view(),
        name="password_reset",
    ),
    path(
        "password_reset/done/",
        PasswordResetDoneView.as_view(),
        name="password_reset_done",
    ),
    path(
        "reset/<uidb64>/<token>/",
        PasswordResetConfirmView.as_view(),
        name="password_reset_confirm",
    ),
    path("password_change/", PasswordChangeView.as_view(), name="password_change"),
    path("delete/", DeleteProfileView.as_view(), name="delete"),
]

main/models.py
from django.contrib.gis.db import models


class DbVersion(models.Model):
    version_id = models.AutoField(primary_key=True)
    version_name = models.CharField(
        unique=True,
        blank=True,
        null=True,
        db_comment="Version name, format : 2024.20.4",
    )
    version_date = models.DateField()

    class Meta:
        managed = False
        db_table = 'terato"."db_version'

main/templates/base.html
{% load i18n %}
{% load render_bundle from webpack_loader %}
{% load webpack_static from webpack_loader %}
{% get_current_language as LANGUAGE_CODE %}
<!DOCTYPE html>
<html lang="{{ LANGUAGE_CODE }}">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="description" content="{% translate "META Description" %}">
        <meta name="keywords" content="{% translate "META Keywords" %}">
        <meta http-equiv="imagetoolbar" content="no" />
        <link rel="icon"
              type="image/png"
              href="{% webpack_static 'main/img/favicon-contour.png' 'MAIN' %}">
        <!-- CSS -->
        {% render_bundle "main" "css" "MAIN" %}
        {% block stylesheet %}
        {% endblock stylesheet %}
        <title>
            {% block title %}
            {% endblock title %}
        </title>
    </head>
    <body>
        <div class="content-wrapper">
            {% include "navbar.html" %}
            {% if messages %}
                <div class="container">
                    {% for message in messages %}
                        <div {% if message.tags %}class="{{ message.tags }}"{% endif %}
                             role="alert">
                            {{ message }}
                            <button type="button"
                                    class="btn-close"
                                    data-bs-dismiss="alert"
                                    aria-label="Close"></button>
                        </div>
                    {% endfor %}
                </div>
            {% endif %}
            <!-- Content block -->
            {% block content %}
            {% endblock content %}
        </div>
        {% include "footer.html" %}
        {% block script %}
            {% render_bundle "base" "js" "MAIN" %}
        {% endblock script %}
    </body>
</html>

main/templates/footer.html
{% load i18n %}
{% load main_tags %}
{% load webpack_static from webpack_loader %}
<footer class="footer">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-11">
                <hr class="mb-3">
                <div class="d-flex justify-content-between px-5 align-items-center text-center">
                    <div class="row w-100 g-0 pb-2 mb-1 justify-content-between align-items-center">
                        <div class="col-lg-auto">
                            <span><a class="link-primary-darker" href="{% url 'contact:contact' %}">
                                {% translate "FOOTER Contacter l'administrateur du site" %}
                            </a></span>
                        </div>
                        <div class="col-lg-auto pb-1">
                            <span class="text-bg-primary-light dot"></span>
                        </div>
                        <div class="col-lg-auto">
                            <span><a class="link-primary-darker" href="{% url 'generic:legals' %}">{% translate "FOOTER Mentions légales" %}</a></span>
                        </div>
                        <div class="col-lg-auto pb-1">
                            <span class="text-bg-primary-light dot"></span>
                        </div>
                        <div class="col-lg-auto">
                            <span><a class="link-primary-darker" href="{% url 'generic:cgu' %}">
                                {% translate "FOOTER Conditions générales d'utilisation" %}
                            </a></span>
                        </div>
                        <div class="col-lg-auto pb-1">
                            <span class="text-bg-primary-light dot"></span>
                        </div>
                        <div class="col-lg-auto">
                            <span>
                                <a href="https://forgemia.inra.fr/diatom/terato" target="_blank">
                                    <span class="link-primary-darker">{% translate "FOOTER Voir le code source" %}</span>
                                    <img class="ps-1 pb-1"
                                         src="{% webpack_static 'main/img/gitlab.svg' 'MAIN' %}"
                                         alt="">
                                </a>
                            </span>
                        </div>
                        <div class="col-lg-auto pb-1">
                            <span class="text-bg-primary-light dot"></span>
                        </div>
                        <div class="col-lg-auto">
                            <span class="text-primary-darker">version {% version %} - © 2023-{% now "Y" %} INRAE</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</footer>

main/templates/lang.html
{% load i18n %}
{% load webpack_static from webpack_loader %}
{% get_current_language as LANGUAGE_CODE %}
{% get_available_languages as languages %}
{% for lang_code, lang_name in languages %}
    {% language lang_code %}
        {% with request.path|slice:'3:' as position %}
            {% with "main/img/"|add:lang_code|add:".png" as file %}
                {% if forloop.counter > 1 %}<span>/</span>{% endif %}
                {% if lang_code == LANGUAGE_CODE %}
                    <img class="mx-1 lang-flag active"
                         src="{% webpack_static file 'MAIN' %}"
                         alt="{{ lang_code }}">
                {% else %}
                    <a href="/{{ lang_code|add:position }}">
                        <img class="mx-2 lang-flag inactive"
                             src="{% webpack_static file 'MAIN' %}"
                             alt="{{ lang_code }}">
                    </a>
                {% endif %}
            {% endwith %}
        {% endwith %}
    {% endlanguage %}
{% endfor %}

main/templates/navbar.html
{% load i18n %}
{% load webpack_static from webpack_loader %}
{% get_available_languages as languages %}
{% get_current_language as LANGUAGE_CODE %}
<!-- Navigation bar -->
<nav id="mainNav"
     class="navbar sticky-top navbar-expand-lg bg-primary-light mb-3">
    <div class="container">
        <a class="navbar-brand nav-link" href="{% url 'generic:home' %}">{% translate "HEADER Nom du site" %}</a>
        <button class="navbar-toggler"
                type="button"
                data-bs-toggle="collapse"
                data-bs-target="#navbarNav"
                aria-controls="navbarNav"
                aria-expanded="false"
                aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse justify-content-between"
             id="navbarNav">
            <ul class="navbar-nav me-auto">
                <li class="nav-item">
                    <a class="nav-link " href="{% url 'atlas:consult:taxons' %}">{% translate "HEADER Consulter" %}</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'atlas:contrib:diatom_upload' %}">{% translate "HEADER Ajouter" %}</a>
                </li>
            </ul>
            <ul class="navbar-nav ms-auto">
                <li class="nav-item dropdown mx-2">
                    <a class="nav-link dropdown-toggle"
                       href="#"
                       id="navbarDropdown"
                       role="button"
                       data-bs-toggle="dropdown"
                       aria-expanded="false">{% translate "HEADER Mon Compte" %}</a>
                    <ul id="nav-menu" class="dropdown-menu" aria-labelledby="navbarDropdown">
                        {% if user.is_authenticated %}
                            <li class="dropdown-item">
                                <a class="nav-link" href="{% url 'users:profile' %}">{% translate "HEADER Profil" %}</a>
                            </li>
                            {% if user.is_staff or user.is_superuser %}
                                <li class="dropdown-item">
                                    <a class="nav-link" href="{% url 'admin:index' %}">{% translate "HEADER Administration" %}</a>
                                </li>
                            {% endif %}
                            <li class="dropdown-item">
                                <form method="post" action="{% url 'users:logout' %}">
                                    {% csrf_token %}
                                    <button class="nav-link" type="submit">{% translate "HEADER Déconnexion" %}</button>
                                </form>
                            </li>
                        {% else %}
                            <li class="dropdown-item">
                                <a class="nav-link" href="{% url 'users:login' %}">{% translate "HEADER Connexion" %}</a>
                            </li>
                        {% endif %}
                    </ul>
                </li>
                <li>{% include "lang.html" %}</li>
            </ul>
        </div>
    </div>
</nav>